# ---------------------------
#
# Build the documentation for
# this project, mainly to see
# that we can
#
# ---------------------------

name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sphinx:
    name: Sphinx
    runs-on: ubuntu-latest
    steps:
    - name: Get source code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Package list
      run: python -m pip list installed

    - name: Build documentation
      run: python -m sphinx -b html -n -W docs/source html

    - name: Upload documentation build
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: html
